### ISSUE TITLE
Error: Player youtube is not supported

### ISSUE THREAD

**Issue by almet** [veo-labs/openveo-player#2]
Hi,

When trying to use the openveo-player with a youtube video, I'm getting this error:

>Error: Player youtube is not supported
at initPlayer (openveo-player.js:871)
    at init (openveo-player.js:885)
    at new controller (openveo-player.js:949)
    at Object.e [as invoke] (angular.js:4443)
    at Q.instance (angular.js:8991)
    at N (angular.js:8101)
    at angular.js:8372
    at angular.js:14551
    at m.$eval (angular.js:15830)
    at m.$digest (angular.js:15641)

I'm taking the examples from the online documentation (everything is viewable at https://github.com/almet/openveo-extractor.py/tree/master/player).

Do you know what the problem could be? Thanks!

**Comment by almet** [comment]
Okay, I found what the issue was: an oldest version of the lib is provided in the default "dist" folder. Ideally, you should either have a way to keep it up to date on master, or remove it from the github files.

Closing.

**Comment by maxime-beguin** [comment]
Hi, 

It seems like you are using the version 1.0.1 of the openveo-player with a more recent version of the documentation. Youtube implementation wasn't available on version 1.0.1. The player is actually in 2.0.2.
Youtube implementation was added in version 1.2.0.

It is actually recommended to use `npm install @openveo/player` to install the player as templates are missing from the dist directory. We have planned to add templates to the generated openveo-player.js but it's not done yet.

**Comment by maxime-beguin** [comment]
You're right, dist folder is not up to date on the master branch. We'll check that. Thanks.

**Comment by maxime-beguin** [comment]
dist folder is now removed from master branch.
