### ISSUE TITLE
Examples are currently broken

### ISSUE THREAD

**Issue by almet** [veo-labs/openveo-player#3]
When trying to make example work, and following the examples given in the documentation, it fails, due to missing modules. The error I'm currently having is:

> [$injector:nomod] Module 'ngCookies' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I'm not an angular.js developer, but from what I've read it is potentially due to a change of politics in the angular project, which decided to remove the dependency from the core.

Do you have any idea of what I should do to make it work? Thanks!

**Comment by maxime-beguin** [comment]
You're right the documentation is missing the dependency on **angular-cookies**. 
You can add [angular-cookies](https://github.com/angular/bower-angular-cookies) after AngularJS :  
`<script type="text/javascript" src="lib/angular/angular.min.js"></script>`
`<script type="text/javascript" src="lib/angular-cookies/angular-cookies.min.js"></script>`

**Comment by almet** [comment]
thanks!

**Comment by maxime-beguin** [comment]
Corrected on version 2.0.3
